<--reporte 1-->
SELECT USUARIOS.NOMBRE, USUARIOS.APELLIDO 
FROM EQUIPO
JOIN SUBS_EQUIPOS ON SUBS_EQUIPOS.EQUIPO_ID_EQUIPO = EQUIPO.ID_EQUIPO 
JOIN USUARIOS ON USUARIOS.ID = SUBS_EQUIPOS.USUARIOS_ID 
WHERE EQUIPO.NOMBRE = 'Equipo1';


<--reporte 2-->
SELECT USUARIOS.EMAIL 
FROM USUARIOS 
WHERE USUARIOS.TIPO_MEMBRECIA ='GRATIS';

SELECT USUARIOS.EMAIL 
FROM USUARIOS 
WHERE USUARIOS.TIPO_MEMBRECIA ='PAGO';


<--reporte 5-->
SELECT USUARIOS.NOMBRE, USUARIOS.APELLIDO 
FROM USUARIOS 
WHERE USUARIOS.PAIS = 'Alemania';


<--reporte 6-->

SELECT USUARIOS.NOMBRE, USUARIOS.APELLIDO 
FROM USUARIOS 
WHERE USUARIOS.GENERO = 'M';

SELECT USUARIOS.NOMBRE, USUARIOS.APELLIDO 
FROM USUARIOS 
WHERE USUARIOS.GENERO = 'F';


<--reporte 7-->
SELECT USUARIOS.NOMBRE, USUARIOS.APELLIDO, trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(USUARIOS.FECHA_NACIMIENTO , 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) AS EDAD
FROM USUARIOS
WHERE trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(USUARIOS.FECHA_NACIMIENTO , 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12)>=20;

<--reporte 8-->
 SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) AS CANT
 FROM NOTICIAS, EMPLEADOS
 WHERE EMPLEADOS.ID_EMPLEADO=NOTICIAS.EMPLEADOS_ID_EMPLEADO
 GROUP BY EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO 
 ORDER BY COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) DESC;

 SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) AS CANT
 FROM NOTICIAS, EMPLEADOS
 WHERE EMPLEADOS.ID_EMPLEADO=NOTICIAS.EMPLEADOS_ID_EMPLEADO
 GROUP BY EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO 
 ORDER BY COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) asc;
 
 <--reporte 9-->
  SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, EQUIPO.NOMBRE ,COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) AS CANT
 FROM EMPLEADOS, NOTICIAS
 JOIN EQUIPO ON EQUIPO.ID_EQUIPO = NOTICIAS.EQUIPO_ID_EQUIPO 
 WHERE EMPLEADOS.ID_EMPLEADO=NOTICIAS.EMPLEADOS_ID_EMPLEADO AND EQUIPO.NOMBRE = 'Equipo1'
 GROUP BY EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, EQUIPO.NOMBRE  
 ORDER BY COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) DESC;

 SELECT EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, EQUIPO.NOMBRE ,COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) AS CANT
 FROM EMPLEADOS, NOTICIAS
 JOIN EQUIPO ON EQUIPO.ID_EQUIPO = NOTICIAS.EQUIPO_ID_EQUIPO 
 WHERE EMPLEADOS.ID_EMPLEADO=NOTICIAS.EMPLEADOS_ID_EMPLEADO AND EQUIPO.NOMBRE = 'Equipo1'
 GROUP BY EMPLEADOS.NOMBRE, EMPLEADOS.APELLIDO, EQUIPO.NOMBRE  
 ORDER BY COUNT(NOTICIAS.EMPLEADOS_ID_EMPLEADO) asc;


